[package]
name = "typical"
version = "0.6.0"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2021"
description = "Algebraic data types for data interchange."
license = "MIT"
documentation = "https://github.com/stepchowfun/typical"
homepage = "https://github.com/stepchowfun/typical"
repository = "https://github.com/stepchowfun/typical"
readme = "README.md"

[dependencies]
colored = "1"
pad = "0.1"
textwrap = "0.14"
unicode-segmentation = "1"

[dependencies.clap]
version = "2"
features = ["wrap_help"]
