[package]
name = "typical"
version = "0.0.0"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2018"
description = "An interface definition language"
license = "MIT"
documentation = "https://github.com/stepchowfun/typical"
homepage = "https://github.com/stepchowfun/typical"
repository = "https://github.com/stepchowfun/typical"
readme = "README.md"

[dependencies]
